# Generated by Django 3.1.2 on 2021-03-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('idtipodocumento', models.CharField(max_length=50)),
                ('documento', models.IntegerField()),
                ('lugarresidencia', models.CharField(max_length=50)),
                ('fechanacimiento', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
